services:
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: [
      "certonly",
      "--webroot",
      "-w", "/var/www/certbot",
      "--force-renewal",
      "--email",
      "thomas.yoshiii@gmail.com",
      "-d",
      "cms.ite4108m.com",
      "--agree-tos"  ]
  namecheap-ddns:
    image: joshuamorris3/namecheap-ddns-update
    build:
      context: ./namecheap-ddns
      dockerfile: Dockerfile
    container_name: namecheap_ddns_updater
    restart: unless-stopped
    env_file: .env
    networks:
      - recipe-network
  nginx:
    container_name: nginx
    image: nginx:1.19.4
    restart: unless-stopped
    volumes:
      - ./reverse-proxy/default.conf:/etc/nginx/conf.d/default.conf
      - ./ite4108m_com:/etc/nginx/certs/
    ports:
      - "80:80"
      - "443:443"
    networks:
      - recipe-network
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
        - 8080:8080
    networks:
      - recipe-network
  # Next.js Application
  app:
    build:
      context: ./smart-recipe-app
      dockerfile: Dockerfile
    container_name: smart-recipe-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:3000
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=your-secret-key-here-change-this-in-production
      - JWT_SECRET=your-jwt-secret-key-change-this-in-production
      - BCRYPT_ROUNDS=12
      - DATABASE_URL=postgresql://postgres:recipe_password_123@database-itp4915m-fyp.cwo5udgju8t2.us-east-1.rds.amazonaws.com:5432/smart_recipe_generator?schema=public
      - LM_STUDIO_BASE_URL=https://hahahagame-gemini-play.deno.dev
      - LM_STUDIO_API_KEY=AIzaSyBzW2lNRzFaZ16T7SEr5HlYfQQVogpMf4U
      - API_REQUEST_LIMIT=100
      - IMAGES_STORAGE_PATH=./public/images/recipes
      - AUDIO_STORAGE_PATH=./public/audio/recipes
    volumes:
      - ./public/images:/app/public/images
      - ./public/audio:/app/public/audio
    networks:
      - recipe-network

  # Development version (optional - for development use)
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: smart-recipe-app-dev
    restart: unless-stopped
    ports:
      - "3003:3002"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:3003
      - NEXTAUTH_URL=http://localhost:3003
      - NEXTAUTH_SECRET=your-secret-key-here-change-this-in-production
      - JWT_SECRET=your-jwt-secret-key-change-this-in-production
      - BCRYPT_ROUNDS=12
      - DATABASE_URL=postgresql://postgres:recipe_password_123@database-itp4915m-fyp.cwo5udgju8t2.us-east-1.rds.amazonaws.com:5432/smart_recipe_generator?schema=public
      - LM_STUDIO_BASE_URL=https://hahahagame-gemini-play.deno.dev
      - LM_STUDIO_API_KEY=AIzaSyBzW2lNRzFaZ16T7SEr5HlYfQQVogpMf4U
      - API_REQUEST_LIMIT=100
      - IMAGES_STORAGE_PATH=./public/images/recipes
      - AUDIO_STORAGE_PATH=./public/audio/recipes
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    networks:
      - recipe-network
    profiles:
      - dev

networks:
  recipe-network:
    driver: bridge
